// GENERATED by scripts/gen-tokens.py from docs/design/build-handoff/tokens.json. Do not edit.

import AppKit
import SwiftUI

/// Semantic colours (handoff §4.1). Light chrome follows the appearance; the dark set is
/// provisional and unapproved (§12 Q4), so the app forces light until Geoff signs one off.
public enum DuoColor {
    /// Toolbar, sheet backgrounds
    public static let ground = Color(nsColor: NSColor.duoDynamic(light: 0xF3F4F6, dark: 0x16181C, name: "ground"))
    /// Light panes, cards, popover, buttons
    public static let pane = Color(nsColor: NSColor.duoDynamic(light: 0xFFFFFF, dark: 0x16181C, name: "pane"))
    /// Selected row, Claude's-additions block
    public static let selected = Color(nsColor: NSColor.duoDynamic(light: 0xE9ECEF, dark: 0x23262B, name: "selected"))
    /// Pane dividers, card borders, field border
    public static let rule = Color(nsColor: NSColor.duoDynamic(light: 0xC9CDD3, dark: 0x2B2F36, name: "rule"))
    /// Button and pill borders, dashed borders, group rule, files rule
    public static let controlEdge = Color(nsColor: NSColor.duoDynamic(light: 0x8B939C, dark: 0x4A4F57, name: "controlEdge"))
    /// Primary text; review and working glyphs; selected-card border
    public static let text = Color(nsColor: NSColor.duoDynamic(light: 0x1F2328, dark: 0xE6E8EB, name: "text"))
    /// Secondary text; idle and resolved glyphs; chevrons
    public static let text2 = Color(nsColor: NSColor.duoDynamic(light: 0x5B636D, dark: 0x9AA1AB, name: "text2"))
    /// The one accent: needs-you glyph, label, chip, question box
    public static let needsYou = Color(nsColor: NSColor.duoDynamic(light: 0xC2410C, dark: 0xF97316, name: "needsYou"))
    /// Text and glyph on the open (filled) chip
    public static let onNeedsYou = Color(nsColor: NSColor.duoDynamic(light: 0xFFFFFF, dark: 0xFFFFFF, name: "onNeedsYou"))
    /// Placeholder in the targets; not built
    public static let placeholderBar = Color(nsColor: NSColor.duoDynamic(light: 0xD5D9DE, dark: 0xD5D9DE, name: "placeholderBar"))
    /// Placeholder in the targets; not built
    public static let placeholderBarOnSelected = Color(nsColor: NSColor.duoDynamic(light: 0xC3C8CE, dark: 0xC3C8CE, name: "placeholderBarOnSelected"))
    /// Dims the whole window behind the search modal. The text colour at 32% (search-handoff).
    public static let scrim = Color(nsColor: NSColor.duoDynamic(light: 0x1F2328, dark: 0x1F2328, name: "scrim").withAlphaComponent(0.32))
    /// Behind sessions that have a terminal open in Duo, so it's easy to jump back in (ENH-7). Provisional, Geoff 2026-10-04: a tint distinct from `selected`, until designed.
    public static let activeTint = Color(nsColor: NSColor.duoDynamic(light: 0xE8F0FA, dark: 0xE8F0FA, name: "activeTint"))

    // Console chrome: the same in every appearance.
    /// Console pane, console tab strips, terminal background
    public static let console = Color(nsColor: .duoFixed(0x15171B))
    /// Rules on the console
    public static let consoleRule = Color(nsColor: .duoFixed(0x2B2F36))
    /// Text on the console, terminal foreground
    public static let consoleText = Color(nsColor: .duoFixed(0xE6E8EB))
    /// Secondary text and inactive tabs on the console
    public static let consoleText2 = Color(nsColor: .duoFixed(0x9AA1AB))
    /// Needs-you glyph on the console
    public static let needsYouOnConsole = Color(nsColor: .duoFixed(0xF97316))
    /// Placeholder in the targets; not built
    public static let placeholderBarOnConsole = Color(nsColor: .duoFixed(0x2F333A))
    /// In the targets only: stands for the TUI's own input box, which Claude Code draws
    public static let tuiInputBorder = Color(nsColor: .duoFixed(0x4A4F57))
}

public enum DuoNSColor {
    public static let ground = NSColor.duoDynamic(light: 0xF3F4F6, dark: 0x16181C, name: "ground")
    public static let pane = NSColor.duoDynamic(light: 0xFFFFFF, dark: 0x16181C, name: "pane")
    public static let selected = NSColor.duoDynamic(light: 0xE9ECEF, dark: 0x23262B, name: "selected")
    public static let rule = NSColor.duoDynamic(light: 0xC9CDD3, dark: 0x2B2F36, name: "rule")
    public static let controlEdge = NSColor.duoDynamic(light: 0x8B939C, dark: 0x4A4F57, name: "controlEdge")
    public static let text = NSColor.duoDynamic(light: 0x1F2328, dark: 0xE6E8EB, name: "text")
    public static let text2 = NSColor.duoDynamic(light: 0x5B636D, dark: 0x9AA1AB, name: "text2")
    public static let needsYou = NSColor.duoDynamic(light: 0xC2410C, dark: 0xF97316, name: "needsYou")
    public static let onNeedsYou = NSColor.duoDynamic(light: 0xFFFFFF, dark: 0xFFFFFF, name: "onNeedsYou")
    public static let placeholderBar = NSColor.duoDynamic(light: 0xD5D9DE, dark: 0xD5D9DE, name: "placeholderBar")
    public static let placeholderBarOnSelected = NSColor.duoDynamic(light: 0xC3C8CE, dark: 0xC3C8CE, name: "placeholderBarOnSelected")
    public static let scrim = NSColor.duoDynamic(light: 0x1F2328, dark: 0x1F2328, name: "scrim").withAlphaComponent(0.32)
    public static let activeTint = NSColor.duoDynamic(light: 0xE8F0FA, dark: 0xE8F0FA, name: "activeTint")
    public static let console = NSColor.duoFixed(0x15171B)
    public static let consoleRule = NSColor.duoFixed(0x2B2F36)
    public static let consoleText = NSColor.duoFixed(0xE6E8EB)
    public static let consoleText2 = NSColor.duoFixed(0x9AA1AB)
    public static let needsYouOnConsole = NSColor.duoFixed(0xF97316)
    public static let placeholderBarOnConsole = NSColor.duoFixed(0x2F333A)
    public static let tuiInputBorder = NSColor.duoFixed(0x4A4F57)
}

/// Radii, borders and fixed sizes (handoff §4.3), in points.
public enum DuoMetric {
    public static let radiusControl: CGFloat = 6.0
    public static let radiusCard: CGFloat = 6.0
    public static let radiusSelection: CGFloat = 6.0
    public static let radiusField: CGFloat = 6.0
    public static let radiusPill: CGFloat = 9.0
    public static let radiusPopover: CGFloat = 10.0
    public static let radiusPlaceholderBar: CGFloat = 3.0
    public static let borderHairline: CGFloat = 1.0
    public static let borderEmphasis: CGFloat = 1.5
    public static let borderFilesDivider: CGFloat = 2.0
    public static let borderTileFocusOutline: CGFloat = 2.0
    public static let toolbarHeight: CGFloat = 38.0
    public static let tabStripHeight: CGFloat = 36.0
    public static let homeSessionTabsHeight: CGFloat = 32.0
    public static let overviewFooterHeight: CGFloat = 34.0
    public static let rowFile: CGFloat = 24.0
    public static let rowTileSession: CGFloat = 24.0
    public static let rowSession: CGFloat = 26.0
    public static let rowGroup: CGFloat = 28.0
    public static let buttonHeight: CGFloat = 26.0
    public static let jumpFieldWidth: CGFloat = 300.0
    public static let jumpFieldHeight: CGFloat = 24.0
    public static let newProjectTileHeight: CGFloat = 38.0
    public static let glyph: CGFloat = 9.0
    public static let paneOverviewHome: CGFloat = 340.0
    public static let paneOverviewActionColumn: CGFloat = 340.0
    public static let paneProjectLeft: CGFloat = 300.0
    public static let paneProjectRight: CGFloat = 460.0
    public static let paneMinHome: CGFloat = 280.0
    public static let paneMinActionColumn: CGFloat = 300.0
    public static let paneMinSessionsAndFiles: CGFloat = 240.0
    public static let paneMinRight: CGFloat = 360.0
    public static let paneMinConsole: CGFloat = 480.0
    public static let peekPopoverWidth: CGFloat = 420.0
    public static let searchModalWidth: CGFloat = 960.0
    public static let searchModalTop: CGFloat = 92.0
    public static let searchModalFieldRowHeight: CGFloat = 52.0
    public static let searchModalListColumnWidth: CGFloat = 420.0
    public static let searchModalBodyMinHeight: CGFloat = 440.0
    public static let searchModalFooterHeight: CGFloat = 34.0
    public static let searchModalRadius: CGFloat = 10.0
    public static let searchRowPadding = EdgeInsets(top: 8.0, leading: 10.0, bottom: 10.0, trailing: 10.0)
    public static let searchRowRadius: CGFloat = 6.0
    public static let searchRowGap: CGFloat = 2.0
    public static let searchRowMetaIndent: CGFloat = 20.0
    public static let searchRowKindIcon: CGFloat = 12.0
    public static let searchRowSnippetMaxLines: CGFloat = 2.0
    public static let searchPreviewPadding = EdgeInsets(top: 14.0, leading: 20.0, bottom: 16.0, trailing: 20.0)
    public static let searchPreviewBlockRadius: CGFloat = 6.0
    public static let searchPreviewBlockPadding = EdgeInsets(top: 10.0, leading: 12.0, bottom: 12.0, trailing: 12.0)
    public static let actionMenuWidth: CGFloat = 300.0
    public static let actionMenuRowHeight: CGFloat = 24.0
    public static let actionMenuPadding: CGFloat = 6.0
    public static let actionMenuRadius: CGFloat = 10.0
    public static let actionMenuAnchorFromRowRight: CGFloat = 8.0
    public static let actionMenuAnchorFromRowTop: CGFloat = 30.0
    public static let sheetTop: CGFloat = 38.0
    public static let sheetPadding: CGFloat = 20.0
    public static let sheetMoveWidth: CGFloat = 460.0
    public static let sheetNewProjectWidth: CGFloat = 520.0
    public static let sheetLabelColumn: CGFloat = 96.0
    public static let sheetRowGap: CGFloat = 12.0
    public static let sheetFieldHeight: CGFloat = 24.0
    public static let sheetFieldPaddingX: CGFloat = 8.0
    public static let sheetDimmedOpacity: CGFloat = 0.55
    public static let noticePaddingX: CGFloat = 20.0
    public static let noticePaddingY: CGFloat = 10.0
    public static let settingsWidth: CGFloat = 680.0
    public static let settingsPaddingX: CGFloat = 24.0
    public static let settingsPaddingY: CGFloat = 20.0
    public static let settingsGroupGap: CGFloat = 18.0
    public static let settingsLabelColumn: CGFloat = 150.0
    public static let settingsRowPaddingX: CGFloat = 12.0
    public static let settingsRowPaddingY: CGFloat = 10.0
    public static let mapHeaderControlHeight: CGFloat = 22.0
    public static let mapFilterWidth: CGFloat = 200.0
    public static let mapOutsideRowWaitWidth: CGFloat = 34.0
    public static let idlePopoverWidth: CGFloat = 460.0
    public static let idlePopoverPadding = EdgeInsets(top: 12.0, leading: 8.0, bottom: 12.0, trailing: 8.0)
    public static let idleRowHeight: CGFloat = 26.0
    public static let idleRowRadius: CGFloat = 6.0
    public static let idleProjectColumnMax: CGFloat = 150.0
    public static let idleAgeColumn: CGFloat = 30.0
    public static let consoleMessagePadding: CGFloat = 24.0
    public static let consoleMessagePaddingHome = EdgeInsets(top: 20.0, leading: 16.0, bottom: 20.0, trailing: 16.0)
    public static let consoleMessageMaxTextWidth: CGFloat = 440.0
    public static let consoleMessageGap: CGFloat = 6.0
    public static let consoleMessageButtonsTop: CGFloat = 8.0
    public static let consoleBarHeight: CGFloat = 40.0
    public static let consoleBarPadding: CGFloat = 16.0
    public static let consoleTabTitleMax: Int = 24
    public static let designWindow = CGSize(width: 1440.0, height: 900.0)
    public static let minimumWindow = CGSize(width: 1280.0, height: 800.0)
}

/// Spacing (handoff §4.3), in points.
public enum DuoSpace {
    public static let panePadding: CGFloat = 16.0
    public static let selectionInset: CGFloat = 8.0
    public static let threadRuleX: CGFloat = 21.0
    public static let cardPadding = EdgeInsets(top: 10.0, leading: 12.0, bottom: 12.0, trailing: 12.0)
    public static let pointerCardPadding = EdgeInsets(top: 8.0, leading: 12.0, bottom: 8.0, trailing: 12.0)
    public static let questionBoxPadding = EdgeInsets(top: 8.0, leading: 10.0, bottom: 8.0, trailing: 10.0)
    public static let buttonPadding = EdgeInsets(top: 4.0, leading: 10.0, bottom: 4.0, trailing: 10.0)
    public static let popoverPadding = EdgeInsets(top: 14.0, leading: 16.0, bottom: 16.0, trailing: 16.0)
    public static let documentPadding = EdgeInsets(top: 22.0, leading: 28.0, bottom: 22.0, trailing: 28.0)
    public static let gapTileRows: CGFloat = 2.0
    public static let gapGlyphToLabel: CGFloat = 6.0
    public static let gapButtonToButton: CGFloat = 6.0
    public static let gapRowItems: CGFloat = 8.0
    public static let gapCardToCard: CGFloat = 10.0
    public static let gapCardContent: CGFloat = 8.0
    public static let gapTileToTile: CGFloat = 10.0
    public static let gapMapColumns: CGFloat = 14.0
    public static let gapToolbarOverview: CGFloat = 16.0
    public static let gapToolbarProject: CGFloat = 8.0
    public static let gapPaneTabs: CGFloat = 18.0
}

/// The terminal's colours (surfaces-handoff DB-2): the 16 ANSI colours, an Increase Contrast set,
/// cursor and selection. Contrast is against `console`.
public enum DuoTerminalPalette {
    public static let ansi: [NSColor] = [.duoFixed(0x2B2F36), .duoFixed(0xE27A85), .duoFixed(0x8CC08A), .duoFixed(0xD6C26B), .duoFixed(0x7FA8E6), .duoFixed(0xC792D8), .duoFixed(0x74C2C9), .duoFixed(0xC9CDD3), .duoFixed(0x7D8590), .duoFixed(0xF09AA3), .duoFixed(0xA9D7A6), .duoFixed(0xE8D98E), .duoFixed(0xA4C3F3), .duoFixed(0xDAB1E7), .duoFixed(0x9BDBE0), .duoFixed(0xFFFFFF)]
    public static let ansiIncreaseContrast: [NSColor] = [.duoFixed(0x4A4F57), .duoFixed(0xF09AA3), .duoFixed(0xA9D7A6), .duoFixed(0xE8D98E), .duoFixed(0xA4C3F3), .duoFixed(0xDAB1E7), .duoFixed(0x9BDBE0), .duoFixed(0xE6E8EB), .duoFixed(0x9AA1AB), .duoFixed(0xF8BDC3), .duoFixed(0xC6E6C3), .duoFixed(0xF2E5B4), .duoFixed(0xC3D8F8), .duoFixed(0xE8CDF0), .duoFixed(0xBEE9EC), .duoFixed(0xFFFFFF)]
    public static let cursor = NSColor.duoFixed(0xE6E8EB)
    public static let textUnderCursor = NSColor.duoFixed(0x15171B)
    public static let selection = NSColor.duoFixed(0x3A4250)
}

/// Type styles (handoff §4.2).
public enum DuoTextStyle: CaseIterable, Sendable {
    case body
    case bodyEmphasis
    case title
    case heading1
    case control
    case chip
    case sectionLabel
    case pill
    case mono
    case monoActiveTab
    case monoPath
    case searchField

    public var spec: DuoTextSpec {
        switch self {
        case .body: DuoTextSpec(size: 13.0, lineHeight: 20.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .bodyEmphasis: DuoTextSpec(size: 13.0, lineHeight: 20.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .title: DuoTextSpec(size: 14.0, lineHeight: 20.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .heading1: DuoTextSpec(size: 18.0, lineHeight: 24.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .control: DuoTextSpec(size: 12.0, lineHeight: 16.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .chip: DuoTextSpec(size: 12.0, lineHeight: 20.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .sectionLabel: DuoTextSpec(size: 11.0, lineHeight: 16.0, weight: .semibold, mono: false, tracking: 0.66, uppercase: true)
        case .pill: DuoTextSpec(size: 11.0, lineHeight: 16.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .mono: DuoTextSpec(size: 12.0, lineHeight: 19.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .monoActiveTab: DuoTextSpec(size: 12.0, lineHeight: 19.0, weight: .medium, mono: true, tracking: 0.0, uppercase: false)
        case .monoPath: DuoTextSpec(size: 11.0, lineHeight: 20.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .searchField: DuoTextSpec(size: 17.0, lineHeight: 24.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        }
    }
}

/// The popover shadow (handoff §4.5): search, the action menu, the idle list, drag cards.
public enum DuoShadow {
    public static let popoverColor = Color(.sRGB, red: 31/255, green: 35/255, blue: 40/255, opacity: 0.22)
    /// SwiftUI's radius is half the CSS blur.
    public static let popoverRadius: CGFloat = 16.0
    public static let popoverX: CGFloat = 0.0
    public static let popoverY: CGFloat = 12.0
    /// Dashed borders (New project tile, drop targets): on, off.
    public static let dashPattern: [CGFloat] = [3.0, 2.0]
}

extension View {
    /// The popover shadow from tokens.json.
    public func duoPopoverShadow() -> some View { shadow(color: DuoShadow.popoverColor, radius: DuoShadow.popoverRadius, x: DuoShadow.popoverX, y: DuoShadow.popoverY) }
}

/// Glyph and icon paths in a 10x10 (or stated) view box (handoff §4.4).
public enum DuoGlyphPath {
    public static let needsYou = "<circle cx='5' cy='5' r='5'/>"
    public static let readyForReview = "<path d='M5 0 10 5 5 10 0 5z'/>"
    public static let working = "<circle cx='5' cy='5' r='4.2' fill='none' stroke-width='1.5'/>"
    public static let idle = "<path d='M1 5h8' fill='none' stroke-width='1.6' stroke-linecap='round'/>"
    public static let resolved = "<path d='M1.5 5.4 4 7.8 8.5 2.4' fill='none' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'/>"
}
