// GENERATED by scripts/gen-tokens.py from docs/design/build-handoff/tokens.json. Do not edit.

import AppKit
import SwiftUI

/// Semantic colours (handoff §4.1). Light chrome follows the appearance; the dark set is
/// provisional and unapproved (§12 Q4), so the app forces light until Geoff signs one off.
public enum DuoColor {
    /// Toolbar, sheet backgrounds
    public static let ground = Color(nsColor: NSColor.duoDynamic(light: 0xF3F4F6, dark: 0x16181C, name: "ground"))
    /// Light panes, cards, popover, buttons
    public static let pane = Color(nsColor: NSColor.duoDynamic(light: 0xFFFFFF, dark: 0x16181C, name: "pane"))
    /// Selected row, Claude's-additions block
    public static let selected = Color(nsColor: NSColor.duoDynamic(light: 0xE9ECEF, dark: 0x23262B, name: "selected"))
    /// Behind a session row, card or tab while its right-click menu is open, darker than selected so it's clear which item the menu acts on (Q-147, undrawn stand-in)
    public static let menuTarget = Color(nsColor: NSColor.duoDynamic(light: 0xD8DCE1, dark: 0x2E3238, name: "menuTarget"))
    /// Pane dividers, card borders, field border
    public static let rule = Color(nsColor: NSColor.duoDynamic(light: 0xC9CDD3, dark: 0x2B2F36, name: "rule"))
    /// Button and pill borders, dashed borders, group rule, files rule
    public static let controlEdge = Color(nsColor: NSColor.duoDynamic(light: 0x8B939C, dark: 0x4A4F57, name: "controlEdge"))
    /// Primary text; review and working glyphs; selected-card border
    public static let text = Color(nsColor: NSColor.duoDynamic(light: 0x1F2328, dark: 0xE6E8EB, name: "text"))
    /// Secondary text; idle and resolved glyphs; chevrons
    public static let text2 = Color(nsColor: NSColor.duoDynamic(light: 0x5B636D, dark: 0x9AA1AB, name: "text2"))
    /// The one accent: needs-you glyph, label, chip, question box
    public static let needsYou = Color(nsColor: NSColor.duoDynamic(light: 0xC2410C, dark: 0xF97316, name: "needsYou"))
    /// Text and glyph on the open (filled) chip
    public static let onNeedsYou = Color(nsColor: NSColor.duoDynamic(light: 0xFFFFFF, dark: 0xFFFFFF, name: "onNeedsYou"))
    /// Placeholder in the targets; not built
    public static let placeholderBar = Color(nsColor: NSColor.duoDynamic(light: 0xD5D9DE, dark: 0xD5D9DE, name: "placeholderBar"))
    /// Placeholder in the targets; not built
    public static let placeholderBarOnSelected = Color(nsColor: NSColor.duoDynamic(light: 0xC3C8CE, dark: 0xC3C8CE, name: "placeholderBarOnSelected"))
    /// Dims the whole window behind the search modal. The text colour at 32% (search-handoff).
    public static let scrim = Color(nsColor: NSColor.duoDynamic(light: 0x1F2328, dark: 0x1F2328, name: "scrim").withAlphaComponent(0.32))
    /// Behind unselected sessions that have a terminal open in Duo, which also read `at prompt` or `working`, so it's easy to jump back in (ENH-7, DL-133).
    public static let activeTint = Color(nsColor: NSColor.duoDynamic(light: 0xE8F0FA, dark: 0xE8F0FA, name: "activeTint"))
    /// The chat transcript's ground, so chat mode stands apart from the white panes beside it (chat-mode-handoff, Sep 1b). Same value as ground.
    public static let chatGround = Color(nsColor: NSColor.duoDynamic(light: 0xF3F4F6, dark: 0xF3F4F6, name: "chatGround"))
    /// Your messages' bubble and your answers to review cards (You chose …); 12.6:1 with text. Not the accent: needsYou keeps its one meaning (chat-mode-handoff).
    public static let chatYou = Color(nsColor: NSColor.duoDynamic(light: 0xDCE6F7, dark: 0xDCE6F7, name: "chatYou"))
    /// Added lines in a diff (chat-mode-handoff)
    public static let diffAddFill = Color(nsColor: NSColor.duoDynamic(light: 0xE6F4EA, dark: 0xE6F4EA, name: "diffAddFill"))
    /// Added-line text and +n counts; 4.5:1 on diffAddFill, 5.1:1 on pane (chat-mode-handoff)
    public static let diffAddText = Color(nsColor: NSColor.duoDynamic(light: 0x2F7D32, dark: 0x2F7D32, name: "diffAddText"))
    /// Removed lines in a diff (chat-mode-handoff)
    public static let diffDelFill = Color(nsColor: NSColor.duoDynamic(light: 0xFDECEA, dark: 0xFDECEA, name: "diffDelFill"))
    /// Removed-line text, −n counts, a failed tool's status and error text; 5.7:1 on diffDelFill, 6.6:1 on pane (chat-mode-handoff)
    public static let diffDelText = Color(nsColor: NSColor.duoDynamic(light: 0xB42318, dark: 0xB42318, name: "diffDelText"))
    /// The border of a failed tool's output box; decoration, the text says failed (chat-mode-handoff)
    public static let toolErrorEdge = Color(nsColor: NSColor.duoDynamic(light: 0xF4C7C1, dark: 0xF4C7C1, name: "toolErrorEdge"))
    /// A Bash step's output box (chat-mode-handoff `tools`; read from the approved board, not in its token additions)
    public static let toolOutputFill = Color(nsColor: NSColor.duoDynamic(light: 0xF8F9FA, dark: 0xF8F9FA, name: "toolOutputFill"))

    // Console chrome: the same in every appearance.
    /// Console pane, console tab strips, terminal background
    public static let console = Color(nsColor: .duoFixed(0x15171B))
    /// Rules on the console
    public static let consoleRule = Color(nsColor: .duoFixed(0x2B2F36))
    /// Behind a console tab while its right-click menu is open, stronger than consoleHover (Q-147, undrawn stand-in)
    public static let consoleMenuTarget = Color(nsColor: .duoFixed(0x2D3138))
    /// Behind a console or Home tab under the pointer, holding its × and name (DL-134)
    public static let consoleHover = Color(nsColor: .duoFixed(0x202329))
    /// Text on the console, terminal foreground
    public static let consoleText = Color(nsColor: .duoFixed(0xE6E8EB))
    /// Secondary text and inactive tabs on the console
    public static let consoleText2 = Color(nsColor: .duoFixed(0x9AA1AB))
    /// Needs-you glyph on the console
    public static let needsYouOnConsole = Color(nsColor: .duoFixed(0xF97316))
    /// Placeholder in the targets; not built
    public static let placeholderBarOnConsole = Color(nsColor: .duoFixed(0x2F333A))
    /// In the targets only: stands for the TUI's own input box, which Claude Code draws
    public static let tuiInputBorder = Color(nsColor: .duoFixed(0x4A4F57))
}

public enum DuoNSColor {
    public static let ground = NSColor.duoDynamic(light: 0xF3F4F6, dark: 0x16181C, name: "ground")
    public static let pane = NSColor.duoDynamic(light: 0xFFFFFF, dark: 0x16181C, name: "pane")
    public static let selected = NSColor.duoDynamic(light: 0xE9ECEF, dark: 0x23262B, name: "selected")
    public static let menuTarget = NSColor.duoDynamic(light: 0xD8DCE1, dark: 0x2E3238, name: "menuTarget")
    public static let rule = NSColor.duoDynamic(light: 0xC9CDD3, dark: 0x2B2F36, name: "rule")
    public static let controlEdge = NSColor.duoDynamic(light: 0x8B939C, dark: 0x4A4F57, name: "controlEdge")
    public static let text = NSColor.duoDynamic(light: 0x1F2328, dark: 0xE6E8EB, name: "text")
    public static let text2 = NSColor.duoDynamic(light: 0x5B636D, dark: 0x9AA1AB, name: "text2")
    public static let needsYou = NSColor.duoDynamic(light: 0xC2410C, dark: 0xF97316, name: "needsYou")
    public static let onNeedsYou = NSColor.duoDynamic(light: 0xFFFFFF, dark: 0xFFFFFF, name: "onNeedsYou")
    public static let placeholderBar = NSColor.duoDynamic(light: 0xD5D9DE, dark: 0xD5D9DE, name: "placeholderBar")
    public static let placeholderBarOnSelected = NSColor.duoDynamic(light: 0xC3C8CE, dark: 0xC3C8CE, name: "placeholderBarOnSelected")
    public static let scrim = NSColor.duoDynamic(light: 0x1F2328, dark: 0x1F2328, name: "scrim").withAlphaComponent(0.32)
    public static let activeTint = NSColor.duoDynamic(light: 0xE8F0FA, dark: 0xE8F0FA, name: "activeTint")
    public static let chatGround = NSColor.duoDynamic(light: 0xF3F4F6, dark: 0xF3F4F6, name: "chatGround")
    public static let chatYou = NSColor.duoDynamic(light: 0xDCE6F7, dark: 0xDCE6F7, name: "chatYou")
    public static let diffAddFill = NSColor.duoDynamic(light: 0xE6F4EA, dark: 0xE6F4EA, name: "diffAddFill")
    public static let diffAddText = NSColor.duoDynamic(light: 0x2F7D32, dark: 0x2F7D32, name: "diffAddText")
    public static let diffDelFill = NSColor.duoDynamic(light: 0xFDECEA, dark: 0xFDECEA, name: "diffDelFill")
    public static let diffDelText = NSColor.duoDynamic(light: 0xB42318, dark: 0xB42318, name: "diffDelText")
    public static let toolErrorEdge = NSColor.duoDynamic(light: 0xF4C7C1, dark: 0xF4C7C1, name: "toolErrorEdge")
    public static let toolOutputFill = NSColor.duoDynamic(light: 0xF8F9FA, dark: 0xF8F9FA, name: "toolOutputFill")
    public static let console = NSColor.duoFixed(0x15171B)
    public static let consoleRule = NSColor.duoFixed(0x2B2F36)
    public static let consoleMenuTarget = NSColor.duoFixed(0x2D3138)
    public static let consoleHover = NSColor.duoFixed(0x202329)
    public static let consoleText = NSColor.duoFixed(0xE6E8EB)
    public static let consoleText2 = NSColor.duoFixed(0x9AA1AB)
    public static let needsYouOnConsole = NSColor.duoFixed(0xF97316)
    public static let placeholderBarOnConsole = NSColor.duoFixed(0x2F333A)
    public static let tuiInputBorder = NSColor.duoFixed(0x4A4F57)
}

/// Radii, borders and fixed sizes (handoff §4.3), in points.
public enum DuoMetric {
    public static let radiusControl: CGFloat = 6.0
    public static let radiusCard: CGFloat = 6.0
    public static let radiusSelection: CGFloat = 6.0
    public static let radiusField: CGFloat = 6.0
    public static let radiusPill: CGFloat = 9.0
    public static let radiusPopover: CGFloat = 10.0
    public static let radiusPlaceholderBar: CGFloat = 3.0
    public static let radiusChatBubble = RectangleCornerRadii(topLeading: 14.0, bottomLeading: 14.0, bottomTrailing: 3.0, topTrailing: 14.0)
    public static let radiusChatCard = RectangleCornerRadii(topLeading: 14.0, bottomLeading: 3.0, bottomTrailing: 14.0, topTrailing: 14.0)
    public static let radiusReviewCard: CGFloat = 14.0
    public static let radiusComposer: CGFloat = 12.0
    public static let radiusChatInlineCode: CGFloat = 4.0
    public static let radiusChatStepBody: CGFloat = 8.0
    public static let radiusChatCodeBlock: CGFloat = 10.0
    public static let radiusChatCheckbox: CGFloat = 3.0
    public static let radiusChatPreviewCode: CGFloat = 6.0
    public static let borderHairline: CGFloat = 1.0
    public static let borderEmphasis: CGFloat = 1.5
    public static let borderFilesDivider: CGFloat = 2.0
    public static let borderTileFocusOutline: CGFloat = 2.0
    public static let toolbarHeight: CGFloat = 38.0
    public static let tabStripHeight: CGFloat = 36.0
    public static let chatStripHeight: CGFloat = 28.0
    public static let deckBarHeight: CGFloat = 44.0
    public static let homeSessionTabsHeight: CGFloat = 32.0
    public static let overviewFooterHeight: CGFloat = 34.0
    public static let rowFile: CGFloat = 24.0
    public static let rowTileSession: CGFloat = 24.0
    public static let rowSession: CGFloat = 26.0
    public static let rowGroup: CGFloat = 28.0
    public static let buttonHeight: CGFloat = 26.0
    public static let jumpFieldWidth: CGFloat = 300.0
    public static let jumpFieldHeight: CGFloat = 24.0
    public static let newProjectTileHeight: CGFloat = 38.0
    public static let glyph: CGFloat = 9.0
    public static let paneOverviewHome: CGFloat = 340.0
    public static let paneOverviewActionColumn: CGFloat = 340.0
    public static let paneProjectLeft: CGFloat = 300.0
    public static let paneProjectRight: CGFloat = 460.0
    public static let paneMinHome: CGFloat = 280.0
    public static let paneMinActionColumn: CGFloat = 300.0
    public static let paneMinSessionsAndFiles: CGFloat = 240.0
    public static let paneMinRight: CGFloat = 360.0
    public static let paneMinConsole: CGFloat = 480.0
    public static let paneMinMap: CGFloat = 440.0
    public static let peekPopoverWidth: CGFloat = 420.0
    public static let searchModalWidth: CGFloat = 960.0
    public static let searchModalTop: CGFloat = 92.0
    public static let searchModalFieldRowHeight: CGFloat = 52.0
    public static let searchModalListColumnWidth: CGFloat = 420.0
    public static let searchModalBodyMinHeight: CGFloat = 440.0
    public static let searchModalFooterHeight: CGFloat = 34.0
    public static let searchModalRadius: CGFloat = 10.0
    public static let searchRowPadding = EdgeInsets(top: 8.0, leading: 10.0, bottom: 10.0, trailing: 10.0)
    public static let searchRowRadius: CGFloat = 6.0
    public static let searchRowGap: CGFloat = 2.0
    public static let searchRowMetaIndent: CGFloat = 20.0
    public static let searchRowKindIcon: CGFloat = 12.0
    public static let searchRowSnippetMaxLines: CGFloat = 2.0
    public static let searchPreviewPadding = EdgeInsets(top: 14.0, leading: 20.0, bottom: 16.0, trailing: 20.0)
    public static let searchPreviewBlockRadius: CGFloat = 6.0
    public static let searchPreviewBlockPadding = EdgeInsets(top: 10.0, leading: 12.0, bottom: 12.0, trailing: 12.0)
    public static let actionMenuWidth: CGFloat = 300.0
    public static let actionMenuRowHeight: CGFloat = 24.0
    public static let actionMenuPadding: CGFloat = 6.0
    public static let actionMenuRadius: CGFloat = 10.0
    public static let actionMenuAnchorFromRowRight: CGFloat = 8.0
    public static let actionMenuAnchorFromRowTop: CGFloat = 30.0
    public static let sheetTop: CGFloat = 38.0
    public static let sheetPadding: CGFloat = 20.0
    public static let sheetMoveWidth: CGFloat = 460.0
    public static let sheetNewProjectWidth: CGFloat = 520.0
    public static let sheetPushWidth: CGFloat = 660.0
    public static let sheetGithubWidth: CGFloat = 640.0
    public static let sheetPushBodyHeight: CGFloat = 64.0
    public static let sheetLabelColumn: CGFloat = 96.0
    public static let sheetRowGap: CGFloat = 12.0
    public static let sheetFieldHeight: CGFloat = 24.0
    public static let sheetFieldPaddingX: CGFloat = 8.0
    public static let sheetDimmedOpacity: CGFloat = 0.55
    public static let noticePaddingX: CGFloat = 20.0
    public static let noticePaddingY: CGFloat = 10.0
    public static let settingsWidth: CGFloat = 680.0
    public static let settingsPaddingX: CGFloat = 24.0
    public static let settingsPaddingY: CGFloat = 20.0
    public static let settingsGroupGap: CGFloat = 18.0
    public static let settingsLabelColumn: CGFloat = 150.0
    public static let settingsRowPaddingX: CGFloat = 12.0
    public static let settingsRowPaddingY: CGFloat = 10.0
    public static let settingsCheckboxIndent: CGFloat = 22.0
    public static let mapHeaderControlHeight: CGFloat = 22.0
    public static let mapFilterWidth: CGFloat = 200.0
    public static let mapOutsideRowWaitWidth: CGFloat = 34.0
    public static let mapColumnMin: CGFloat = 220.0
    public static let sessionListProjectWidth: CGFloat = 150.0
    public static let sessionListTaskWidth: CGFloat = 150.0
    public static let sessionListWaitWidth: CGFloat = 64.0
    public static let sessionListNeedsLineHeight: CGFloat = 28.0
    public static let sessionListTwoLineHeight: CGFloat = 44.0
    public static let sessionListTwoLineBelow: CGFloat = 520.0
    public static let sessionListRowInset: CGFloat = 8.0
    public static let sessionListToggleSegmentPadding: CGFloat = 10.0
    public static let sessionListToggleIconGap: CGFloat = 5.0
    public static let rowActionSize: CGFloat = 18.0
    public static let rowActionRadius: CGFloat = 4.0
    public static let rowActionGlyph: CGFloat = 14.0
    public static let tabCloseSize: CGFloat = 16.0
    public static let tabCloseRadius: CGFloat = 4.0
    public static let tabCloseGlyph: CGFloat = 10.0
    public static let tabCloseStroke: CGFloat = 1.5
    public static let tabCloseTitleGap: CGFloat = 1.0
    public static let tabHoverRadius: CGFloat = 5.0
    public static let tabHoverHeight: CGFloat = 24.0
    public static let tabHoverInset: CGFloat = 7.0
    public static let repoLineButtonHeight: CGFloat = 20.0
    public static let repoLineButtonFont: CGFloat = 11.0
    public static let repoLineButtonPaddingX: CGFloat = 8.0
    public static let taskBoardHeaderHeight: CGFloat = 38.0
    public static let taskBoardHeaderPaddingX: CGFloat = 16.0
    public static let taskBoardFilterWidth: CGFloat = 180.0
    public static let taskBoardControlHeight: CGFloat = 22.0
    public static let taskBoardLanesPadding = EdgeInsets(top: 10.0, leading: 16.0, bottom: 16.0, trailing: 16.0)
    public static let taskBoardLaneGap: CGFloat = 10.0
    public static let taskBoardLaneHeaderHeight: CGFloat = 22.0
    public static let taskBoardLaneBodyPadding: CGFloat = 6.0
    public static let taskBoardCardGap: CGFloat = 6.0
    public static let taskBoardLaneMin: CGFloat = 150.0
    public static let taskBoardLaneScrollWidth: CGFloat = 200.0
    public static let taskBoardFoldsBelow: CGFloat = 900.0
    public static let taskBoardScrollsBelow: CGFloat = 640.0
    public static let taskBoardDoneStripWidth: CGFloat = 34.0
    public static let taskBoardCardPadding = EdgeInsets(top: 8.0, leading: 10.0, bottom: 9.0, trailing: 10.0)
    public static let taskBoardCardLineGap: CGFloat = 3.0
    public static let taskBoardMetaIndent: CGFloat = 17.0
    public static let taskBoardTitleGap: CGFloat = 7.0
    public static let taskBoardSessionRowHeight: CGFloat = 22.0
    public static let taskBoardSessionRowGap: CGFloat = 3.0
    public static let taskBoardSessionRowsMax: CGFloat = 3.0
    public static let taskBoardSessionsTop: CGFloat = 5.0
    public static let taskBoardSessionsRule: CGFloat = 6.0
    public static let taskBoardSwitchHeight: CGFloat = 22.0
    public static let taskBoardSwitchPaddingX: CGFloat = 10.0
    public static let taskBoardAddColumnWidth: CGFloat = 170.0
    public static let taskBoardAddColumnIdle: CGFloat = 26.0
    public static let idlePopoverWidth: CGFloat = 460.0
    public static let idlePopoverPadding = EdgeInsets(top: 12.0, leading: 8.0, bottom: 12.0, trailing: 8.0)
    public static let idleRowHeight: CGFloat = 26.0
    public static let idleRowRadius: CGFloat = 6.0
    public static let idleProjectColumnMax: CGFloat = 150.0
    public static let idleAgeColumn: CGFloat = 30.0
    public static let consoleMessagePadding: CGFloat = 24.0
    public static let consoleMessagePaddingHome = EdgeInsets(top: 20.0, leading: 16.0, bottom: 20.0, trailing: 16.0)
    public static let consoleMessageMaxTextWidth: CGFloat = 440.0
    public static let consoleMessageGap: CGFloat = 6.0
    public static let consoleMessageButtonsTop: CGFloat = 8.0
    public static let consoleBarHeight: CGFloat = 40.0
    public static let consoleBarPadding: CGFloat = 16.0
    public static let consoleTabTitleMax: Int = 24
    public static let designWindow = CGSize(width: 1440.0, height: 900.0)
    public static let minimumWindow = CGSize(width: 1280.0, height: 800.0)
}

/// Spacing (handoff §4.3), in points.
public enum DuoSpace {
    public static let panePadding: CGFloat = 16.0
    public static let selectionInset: CGFloat = 8.0
    public static let threadRuleX: CGFloat = 21.0
    public static let chatColumnInset: CGFloat = 24.0
    public static let chatCardTrailing: CGFloat = 36.0
    public static let chatBubbleMax: CGFloat = 440.0
    public static let cardPadding = EdgeInsets(top: 10.0, leading: 12.0, bottom: 12.0, trailing: 12.0)
    public static let pointerCardPadding = EdgeInsets(top: 8.0, leading: 12.0, bottom: 8.0, trailing: 12.0)
    public static let questionBoxPadding = EdgeInsets(top: 8.0, leading: 10.0, bottom: 8.0, trailing: 10.0)
    public static let buttonPadding = EdgeInsets(top: 4.0, leading: 10.0, bottom: 4.0, trailing: 10.0)
    public static let popoverPadding = EdgeInsets(top: 14.0, leading: 16.0, bottom: 16.0, trailing: 16.0)
    public static let documentPadding = EdgeInsets(top: 22.0, leading: 28.0, bottom: 22.0, trailing: 28.0)
    public static let gapTileRows: CGFloat = 2.0
    public static let gapGlyphToLabel: CGFloat = 6.0
    public static let gapButtonToButton: CGFloat = 6.0
    public static let gapRowItems: CGFloat = 8.0
    public static let gapCardToCard: CGFloat = 10.0
    public static let gapCardContent: CGFloat = 8.0
    public static let gapTileToTile: CGFloat = 10.0
    public static let gapMapColumns: CGFloat = 14.0
    public static let gapToolbarOverview: CGFloat = 16.0
    public static let gapToolbarProject: CGFloat = 8.0
    public static let gapPaneTabs: CGFloat = 24.0
    public static let gapAboveDocumentHeading: CGFloat = 4.0
}

/// The terminal's colours (surfaces-handoff DB-2): the 16 ANSI colours, an Increase Contrast set,
/// cursor and selection. Contrast is against `console`.
public enum DuoTerminalPalette {
    public static let ansi: [NSColor] = [.duoFixed(0x2B2F36), .duoFixed(0xE27A85), .duoFixed(0x8CC08A), .duoFixed(0xD6C26B), .duoFixed(0x7FA8E6), .duoFixed(0xC792D8), .duoFixed(0x74C2C9), .duoFixed(0xC9CDD3), .duoFixed(0x7D8590), .duoFixed(0xF09AA3), .duoFixed(0xA9D7A6), .duoFixed(0xE8D98E), .duoFixed(0xA4C3F3), .duoFixed(0xDAB1E7), .duoFixed(0x9BDBE0), .duoFixed(0xFFFFFF)]
    public static let ansiIncreaseContrast: [NSColor] = [.duoFixed(0x4A4F57), .duoFixed(0xF09AA3), .duoFixed(0xA9D7A6), .duoFixed(0xE8D98E), .duoFixed(0xA4C3F3), .duoFixed(0xDAB1E7), .duoFixed(0x9BDBE0), .duoFixed(0xE6E8EB), .duoFixed(0x9AA1AB), .duoFixed(0xF8BDC3), .duoFixed(0xC6E6C3), .duoFixed(0xF2E5B4), .duoFixed(0xC3D8F8), .duoFixed(0xE8CDF0), .duoFixed(0xBEE9EC), .duoFixed(0xFFFFFF)]
    public static let cursor = NSColor.duoFixed(0xE6E8EB)
    public static let textUnderCursor = NSColor.duoFixed(0x15171B)
    public static let selection = NSColor.duoFixed(0x3A4250)
}

/// Type styles (handoff §4.2).
public enum DuoTextStyle: CaseIterable, Sendable {
    case body
    case bodyEmphasis
    case title
    case heading1
    case control
    case chip
    case sectionLabel
    case pill
    case mono
    case monoActiveTab
    case monoPath
    case searchField
    case chatBody
    case chatBodyEmphasis
    case chatHeading
    case chatHeading1
    case chatHeading3
    case chatMeta
    case chatInlineCode
    case chatDiff
    case chatPreview
    case chatPlanHeading
    case cardTitle

    public var spec: DuoTextSpec {
        switch self {
        case .body: DuoTextSpec(size: 13.0, lineHeight: 20.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .bodyEmphasis: DuoTextSpec(size: 13.0, lineHeight: 20.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .title: DuoTextSpec(size: 14.0, lineHeight: 20.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .heading1: DuoTextSpec(size: 18.0, lineHeight: 24.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .control: DuoTextSpec(size: 12.0, lineHeight: 16.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .chip: DuoTextSpec(size: 12.0, lineHeight: 20.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .sectionLabel: DuoTextSpec(size: 11.0, lineHeight: 16.0, weight: .semibold, mono: false, tracking: 0.66, uppercase: true)
        case .pill: DuoTextSpec(size: 11.0, lineHeight: 16.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .mono: DuoTextSpec(size: 12.0, lineHeight: 19.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .monoActiveTab: DuoTextSpec(size: 12.0, lineHeight: 19.0, weight: .medium, mono: true, tracking: 0.0, uppercase: false)
        case .monoPath: DuoTextSpec(size: 11.0, lineHeight: 20.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .searchField: DuoTextSpec(size: 17.0, lineHeight: 24.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .chatBody: DuoTextSpec(size: 14.0, lineHeight: 22.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .chatBodyEmphasis: DuoTextSpec(size: 14.0, lineHeight: 22.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .chatHeading: DuoTextSpec(size: 16.0, lineHeight: 24.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .chatHeading1: DuoTextSpec(size: 18.0, lineHeight: 26.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .chatHeading3: DuoTextSpec(size: 14.0, lineHeight: 22.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .chatMeta: DuoTextSpec(size: 12.0, lineHeight: 16.0, weight: .regular, mono: false, tracking: 0.0, uppercase: false)
        case .chatInlineCode: DuoTextSpec(size: 12.5, lineHeight: 22.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .chatDiff: DuoTextSpec(size: 11.5, lineHeight: 18.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .chatPreview: DuoTextSpec(size: 10.5, lineHeight: 14.0, weight: .regular, mono: true, tracking: 0.0, uppercase: false)
        case .chatPlanHeading: DuoTextSpec(size: 15.0, lineHeight: 22.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        case .cardTitle: DuoTextSpec(size: 13.0, lineHeight: 18.0, weight: .semibold, mono: false, tracking: 0.0, uppercase: false)
        }
    }
}

/// Motion (DL-129, DL-130), in seconds. None of it runs with Reduce Motion; build it with `DuoMotionToken`.
public enum DuoMotion {
    public static let paneToggle: Double = 0.2
    public static let scrimIn: Double = 0.12
    public static let scrimOut: Double = 0.1
    public static let tileIn: Double = 0.15
    public static let altitude: Double = 0.15
    public static let rowIn: Double = 0.15
    public static let rowOut: Double = 0.15
    public static let rowMove: Double = 0.2
    public static let rowHold: Double = 5.0
    public static let fold: Double = 0.18
    public static let sheetIn: Double = 0.2
    public static let sheetOut: Double = 0.15
    public static let sheetSwap: Double = 0.12
    public static let cardIn: Double = 0.2
    public static let cardOut: Double = 0.15
    public static let lift: Double = 0.2
    public static let landed: Double = 0.4
    public static let tabIn: Double = 0.15
    public static let tabOut: Double = 0.12
    public static let tabMove: Double = 0.15
    public static let noticeIn: Double = 0.15
    public static let noticeOut: Double = 0.12
    public static let chipIn: Double = 0.15
    public static let count: Double = 0.2
    public static let highlightIn: Double = 0.2
    public static let highlightOut: Double = 0.6
    public static let slide: Double = 0.25
    public static let outline: Double = 0.08
    public static let messageIn: Double = 0.12
    public static let dropIn: Double = 0.1
}

/// How a motion eases (DL-130): arriving eases out, leaving eases in, moving eases in and out.
public enum DuoEase: Sendable { case out, `in`, inOut, none }

/// One motion token: its duration and its easing.
public enum DuoMotionToken: String, CaseIterable, Sendable {
    case paneToggle, scrimIn, scrimOut, tileIn, altitude, rowIn, rowOut, rowMove, rowHold, fold, sheetIn, sheetOut, sheetSwap, cardIn, cardOut, lift, landed, tabIn, tabOut, tabMove, noticeIn, noticeOut, chipIn, count, highlightIn, highlightOut, slide, outline, messageIn, dropIn
    public var seconds: Double {
        switch self {
        case .paneToggle: DuoMotion.paneToggle
        case .scrimIn: DuoMotion.scrimIn
        case .scrimOut: DuoMotion.scrimOut
        case .tileIn: DuoMotion.tileIn
        case .altitude: DuoMotion.altitude
        case .rowIn: DuoMotion.rowIn
        case .rowOut: DuoMotion.rowOut
        case .rowMove: DuoMotion.rowMove
        case .rowHold: DuoMotion.rowHold
        case .fold: DuoMotion.fold
        case .sheetIn: DuoMotion.sheetIn
        case .sheetOut: DuoMotion.sheetOut
        case .sheetSwap: DuoMotion.sheetSwap
        case .cardIn: DuoMotion.cardIn
        case .cardOut: DuoMotion.cardOut
        case .lift: DuoMotion.lift
        case .landed: DuoMotion.landed
        case .tabIn: DuoMotion.tabIn
        case .tabOut: DuoMotion.tabOut
        case .tabMove: DuoMotion.tabMove
        case .noticeIn: DuoMotion.noticeIn
        case .noticeOut: DuoMotion.noticeOut
        case .chipIn: DuoMotion.chipIn
        case .count: DuoMotion.count
        case .highlightIn: DuoMotion.highlightIn
        case .highlightOut: DuoMotion.highlightOut
        case .slide: DuoMotion.slide
        case .outline: DuoMotion.outline
        case .messageIn: DuoMotion.messageIn
        case .dropIn: DuoMotion.dropIn
        }
    }
    public var ease: DuoEase {
        switch self {
        case .paneToggle: .inOut
        case .scrimIn: .out
        case .scrimOut: .`in`
        case .tileIn: .out
        case .altitude: .out
        case .rowIn: .out
        case .rowOut: .`in`
        case .rowMove: .inOut
        case .rowHold: .none
        case .fold: .inOut
        case .sheetIn: .out
        case .sheetOut: .`in`
        case .sheetSwap: .inOut
        case .cardIn: .out
        case .cardOut: .`in`
        case .lift: .out
        case .landed: .out
        case .tabIn: .out
        case .tabOut: .`in`
        case .tabMove: .inOut
        case .noticeIn: .out
        case .noticeOut: .`in`
        case .chipIn: .out
        case .count: .out
        case .highlightIn: .out
        case .highlightOut: .inOut
        case .slide: .inOut
        case .outline: .out
        case .messageIn: .out
        case .dropIn: .out
        }
    }
}

/// The popover shadow (handoff §4.5): search, the action menu, the idle list, drag cards.
public enum DuoShadow {
    public static let popoverColor = Color(.sRGB, red: 31/255, green: 35/255, blue: 40/255, opacity: 0.22)
    /// SwiftUI's radius is half the CSS blur.
    public static let popoverRadius: CGFloat = 16.0
    public static let popoverX: CGFloat = 0.0
    public static let popoverY: CGFloat = 12.0
    /// Dashed borders (New project tile, drop targets): on, off.
    public static let dashPattern: [CGFloat] = [3.0, 2.0]
}

extension View {
    /// The popover shadow from tokens.json.
    public func duoPopoverShadow() -> some View { shadow(color: DuoShadow.popoverColor, radius: DuoShadow.popoverRadius, x: DuoShadow.popoverX, y: DuoShadow.popoverY) }
}

/// Glyph and icon paths in a 10x10 (or stated) view box (handoff §4.4).
public enum DuoGlyphPath {
    public static let needsYou = "<circle cx='5' cy='5' r='5'/>"
    public static let readyForReview = "<path d='M5 0 10 5 5 10 0 5z'/>"
    public static let working = "<circle cx='5' cy='5' r='4.2' fill='none' stroke-width='1.5'/>"
    public static let idle = "<path d='M1 5h8' fill='none' stroke-width='1.6' stroke-linecap='round'/>"
    public static let resolved = "<path d='M1.5 5.4 4 7.8 8.5 2.4' fill='none' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'/>"
}
