import CryptoKit
import Foundation

/// What Duo installs so Claude sessions anywhere know about `duo2` (DL-74, approach C of
/// `docs/design/cli-teaching.md`), and the loop that keeps it current: a short managed block in
/// `~/.claude/CLAUDE.md`, a generated `duo2` skill, and `~/.local/bin/duo2` linked to the app.
///
/// Lessons from legacy Duo, kept as rules:
/// - Everything is generated from the action registry, so it never names a verb that doesn't exist.
/// - Everything is rewritten at every launch (legacy wrote "only if missing", so fixes never
///   reached anyone), unless the user edited it: a file whose hash isn't what Duo wrote is left
///   alone and reported by `duo2 doctor`.
/// - The block, once removed by the user, is never added back.
/// - One manifest lists what Duo wrote; `duo2 uninstall` removes exactly that.
/// - Markers are distinct from legacy's (`duo:managed-v…`), so neither tool touches the other's.
/// - The newest format wins: an older Duo never downgrades what a newer one wrote.
public enum Installer {
    /// Bump when the installed shape changes.
    public static let format = 1

    /// Checks and acceptance runs only: puts everything under one folder instead of the real home.
    /// `DUO_INSTALL_ROOT` sets it for the app and duo2, so a walk can exercise the real loop on a fake.
    nonisolated(unsafe) public static var testRoot: URL? = ProcessInfo.processInfo.environment["DUO_INSTALL_ROOT"].flatMap { $0.isEmpty ? nil : URL(fileURLWithPath: $0) }

    public static var claudeDir: URL { testRoot?.appending(path: "claude") ?? LegacyDuo.claudeDir }
    public static var claudeMD: URL { claudeDir.appending(path: "CLAUDE.md") }
    public static var skillFile: URL { claudeDir.appending(path: "skills/duo2/SKILL.md") }
    public static var link: URL { (testRoot ?? FileManager.default.homeDirectoryForCurrentUser).appending(path: ".local/bin/duo2") }
    static var manifestFile: URL { testRoot?.appending(path: "installed.json") ?? ControlEndpoint.file.deletingLastPathComponent().appending(path: "installed.json") }

    static let begin = "<!-- duo2:begin"
    static let end = "<!-- duo2:end -->"
    static let blockRE = try! NSRegularExpression(pattern: #"\n?<!-- duo2:begin[^>]*-->[\s\S]*?<!-- duo2:end -->\n?"#)

    // MARK: What gets written

    /// The block every Claude session on this Mac loads: short (it's always-on), generated.
    public static func block() -> String {
        """
        \(begin) v\(format): written by the Duo app. Duo rewrites what's between these markers; remove the whole block and it won't come back. -->
        ## Duo
        The user runs Duo, a Mac app that organizes their Claude Code sessions into projects. When `duo2` is on PATH, it reaches Duo: \
        everything the user can do in Duo, you can do with it. Run `duo2 help` to see how; prefer it for anything about \
        their projects, sessions or the documents they have open, and `duo2 search "<question>"` for finding things across projects. \
        If `duo2` can't reach Duo, `duo2 doctor` says why.
        \(end)
        """
    }

    /// The skill: when to use which family; details come from `duo2 help <family>`.
    public static func skill() -> String {
        let families = ActionFamily.allCases.map { f in
            "- **\(f.title)** (`duo2 help \(f.rawValue)`): " + DuoAction.all.filter { $0.family == f }.map { "`\($0.verb)`" }.joined(separator: ", ")
        }.joined(separator: "\n")
        return """
        ---
        name: duo2
        description: Use the Duo app's `duo2` command whenever the user mentions Duo, their projects or sessions, "what I selected", a document or HTML page they have open, sending something to another session, or finding something across projects. Everything the user can do in Duo, duo2 can do.
        ---

        <!-- Generated by the Duo app from its action registry (format \(format)). Duo rewrites this file at launch unless you edit it. -->

        # duo2

        `duo2` talks to the running Duo app. Every verb takes `--json`; errors go to stderr with a non-zero exit.

        ## When to reach for it

        - The user says "this", "here", "the selected text", "this button": run `duo2 selection` first.
        - Before editing a file: `duo2 doc status <file>`. If it's open in Duo, use `duo2 doc replace` or `duo2 doc insert` so the user sees the change highlighted.
        - Questions across projects or about meaning: `duo2 search "<question>"` before grep.
        - Showing the user something: `duo2 open <project>`, `duo2 doc open <path>`.
        - Narrate long work: `duo2 session note "<one line>"`; hand back with `duo2 session next "<one line>"`.
        - Moves and merges ask the user to confirm in Duo; wait for the answer.

        ## Families

        \(families)

        Run `duo2 help <family>` for arguments before using a verb you haven't used in this session.
        """
    }

    // MARK: The manifest

    public struct Manifest: Codable, Equatable {
        public var format = Installer.format
        public var blockHash: String?
        public var skillHash: String?
        public var linkTarget: String?
        /// The user removed the block; never add it back.
        public var blockRemovedByUser = false
        /// The consent list the user answered, and how.
        public var consentHash: String?
        public var consented = false
    }

    public static func manifest() -> Manifest {
        (try? JSONDecoder().decode(Manifest.self, from: Data(contentsOf: manifestFile))) ?? Manifest()
    }

    static func save(_ m: Manifest) {
        try? FileManager.default.createDirectory(at: manifestFile.deletingLastPathComponent(), withIntermediateDirectories: true)
        try? JSONEncoder().encode(m).write(to: manifestFile, options: .atomic)
    }

    static func hash(_ s: String) -> String { SHA256.hash(data: Data(s.utf8)).map { String(format: "%02x", $0) }.joined() }

    // MARK: Consent (DL-75)

    /// Every change, in words, for the consent alert. Its hash decides when to ask again.
    public static func plannedChanges(cli: String) -> [String] {
        [
            "Add a short \"Duo\" section to \(claudeMD.path), between <!-- duo2:begin --> and <!-- duo2:end --> markers (\(block().split(separator: " ").count) words; it loads into every Claude session).",
            "Write a duo2 skill to \(skillFile.path).",
            "Link \(link.path) to \(cli), so duo2 works in any terminal.",
            "Keep these current each time Duo starts. Anything you edit is left alone; `duo2 uninstall` removes all of it.",
        ]
    }

    /// The same changes as the install sheet lists them: what, and where (S3-3).
    public static func plannedItems(cli: String) -> [(what: String, path: String)] {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        let short = { (p: String) in p.hasPrefix(home) ? "~" + p.dropFirst(home.count) : p }
        return [("Add a short Duo section, between duo2 markers (\(block().split(separator: " ").count) words)", short(claudeMD.path)),
                ("Write the duo2 skill", short(skillFile.path)),
                ("Put duo2 on your PATH", short(link.path))]
    }

    public static func consentHash(cli: String) -> String { hash(plannedChanges(cli: cli).joined(separator: "\n") + "\(format)") }

    /// Whether to ask: never answered, or the list changed since.
    public static func needsConsent(cli: String) -> Bool { manifest().consentHash != consentHash(cli: cli) }

    public static func recordConsent(_ yes: Bool, cli: String) {
        var m = manifest()
        m.consentHash = consentHash(cli: cli)
        m.consented = yes
        save(m)
    }

    // MARK: Install, update, uninstall

    public struct Report: Sendable {
        public var lines: [String] = []
    }

    /// Writes or refreshes everything (only with consent). Idempotent; safe at every launch.
    @discardableResult
    public static func install(cli: String) -> Report {
        var m = manifest()
        var r = Report()
        guard m.consented else { r.lines.append("Not installed: Duo asked and you said not now. `duo2 install` installs it."); return r }
        guard m.format <= format else { r.lines.append("A newer Duo installed these (format \(m.format)); this one leaves them alone."); return r }
        m.format = format
        let fm = FileManager.default

        // The block.
        let current = (try? String(contentsOf: claudeMD, encoding: .utf8)) ?? ""
        let existing = firstBlock(in: current)
        if m.blockRemovedByUser {
            r.lines.append("CLAUDE.md block: you removed it, so Duo doesn't add it back.")
        } else if let existing, m.blockHash != nil, hash(existing) != m.blockHash!, existing != block() {
            r.lines.append("CLAUDE.md block: edited by you, left alone.")
        } else if existing == nil, m.blockHash != nil {
            m.blockRemovedByUser = true
            m.blockHash = nil
            r.lines.append("CLAUDE.md block: you removed it, so Duo won't add it back.")
        } else {
            let text = existing == nil
                ? current + (current.isEmpty || current.hasSuffix("\n\n") ? "" : current.hasSuffix("\n") ? "\n" : "\n\n") + block() + "\n"
                : replaceBlock(in: current, with: block())
            if text != current {
                do {
                    try fm.createDirectory(at: claudeDir, withIntermediateDirectories: true)
                    try Data(text.utf8).write(to: claudeMD, options: .atomic)
                    r.lines.append("CLAUDE.md block: \(existing == nil ? "added" : "updated").")
                } catch { r.lines.append("CLAUDE.md block: couldn't write (\(error.localizedDescription)).") }
            }
            m.blockHash = hash(block())
        }

        // The skill.
        let skillNow = try? String(contentsOf: skillFile, encoding: .utf8)
        if let skillNow, let h = m.skillHash, hash(skillNow) != h, skillNow != skill() {
            r.lines.append("Skill: edited by you, left alone.")
        } else if skillNow != skill() {
            do {
                try fm.createDirectory(at: skillFile.deletingLastPathComponent(), withIntermediateDirectories: true)
                try Data(skill().utf8).write(to: skillFile, options: .atomic)
                m.skillHash = hash(skill())
                r.lines.append("Skill: \(skillNow == nil ? "written" : "updated").")
            } catch { r.lines.append("Skill: couldn't write (\(error.localizedDescription)).") }
        } else { m.skillHash = hash(skill()) }

        // The link: replaced only if it's Duo's (a link to some Duo.app's duo2).
        let dest = try? fm.destinationOfSymbolicLink(atPath: link.path)
        if fm.fileExists(atPath: link.path) || dest != nil, !(dest.map(isDuoCLI) ?? false) {
            r.lines.append("\(link.path): something else is there, left alone.")
        } else if dest != cli {
            do {
                try fm.createDirectory(at: link.deletingLastPathComponent(), withIntermediateDirectories: true)
                if dest != nil { try fm.removeItem(at: link) }
                try fm.createSymbolicLink(atPath: link.path, withDestinationPath: cli)
                m.linkTarget = cli
                r.lines.append("\(link.path) → \(cli).")
            } catch { r.lines.append("Link: couldn't write (\(error.localizedDescription)).") }
        } else { m.linkTarget = cli }

        save(m)
        return r
    }

    /// Removes exactly what the manifest says Duo wrote. Edited files stay, with a note.
    @discardableResult
    public static func uninstall() -> Report {
        var m = manifest()
        var r = Report()
        let fm = FileManager.default
        if let text = try? String(contentsOf: claudeMD, encoding: .utf8), let b = firstBlock(in: text) {
            if m.blockHash == nil || hash(b) == m.blockHash! || b == block() {
                try? Data(replaceBlock(in: text, with: nil).utf8).write(to: claudeMD, options: .atomic)
                r.lines.append("Removed the Duo block from \(claudeMD.path).")
            } else { r.lines.append("Left the Duo block in \(claudeMD.path): you edited it. Delete it by hand if you like.") }
        }
        if let s = try? String(contentsOf: skillFile, encoding: .utf8) {
            if m.skillHash.map({ hash(s) == $0 }) ?? false || s == skill() {
                try? fm.removeItem(at: skillFile.deletingLastPathComponent())
                r.lines.append("Removed \(skillFile.deletingLastPathComponent().path).")
            } else { r.lines.append("Left \(skillFile.path): you edited it.") }
        }
        if let dest = try? fm.destinationOfSymbolicLink(atPath: link.path), isDuoCLI(dest) {
            try? fm.removeItem(at: link)
            r.lines.append("Removed \(link.path).")
        }
        m.blockHash = nil; m.skillHash = nil; m.linkTarget = nil; m.consented = false
        save(m)
        if r.lines.isEmpty { r.lines.append("Nothing of Duo's was installed.") }
        return r
    }

    /// What's installed and in what state, for `duo2 doctor`.
    public static func status(cli: String?) -> [String] {
        let m = manifest()
        var out: [String] = []
        if !m.consented { out.append("Duo's Claude instructions aren't installed (you said not now, or Duo hasn't asked yet). `duo2 install` installs them; Duo's own sessions don't need them.") }
        let text = (try? String(contentsOf: claudeMD, encoding: .utf8)) ?? ""
        switch firstBlock(in: text) {
        case nil: out.append("CLAUDE.md block: \(m.blockRemovedByUser ? "removed by you (Duo won't add it back)" : "not present").")
        case let b?: out.append("CLAUDE.md block: \(b == block() ? "current" : m.blockHash.map { hash(b) == $0 } == true ? "from an older Duo (updates at launch)" : "edited by you (left alone)").")
        }
        if let s = try? String(contentsOf: skillFile, encoding: .utf8) {
            out.append("Skill: \(s == skill() ? "current" : m.skillHash.map { hash(s) == $0 } == true ? "from an older Duo (updates at launch)" : "edited by you (left alone)") (\(skillFile.path)).")
        } else { out.append("Skill: not installed.") }
        if let dest = try? FileManager.default.destinationOfSymbolicLink(atPath: link.path) {
            out.append("\(link.path) → \(dest)\(cli.map { dest == $0 ? "" : " (Duo relinks it to \($0) at launch)" } ?? "").")
        } else { out.append("\(link.path): not linked.") }
        return out
    }

    // MARK: Helpers

    static func firstBlock(in text: String) -> String? {
        let ns = text as NSString
        guard let m = blockRE.firstMatch(in: text, range: NSRange(location: 0, length: ns.length)) else { return nil }
        return ns.substring(with: m.range).trimmingCharacters(in: .newlines)
    }

    static func replaceBlock(in text: String, with new: String?) -> String {
        let ns = text as NSString
        guard let m = blockRE.firstMatch(in: text, range: NSRange(location: 0, length: ns.length)) else { return text }
        return ns.replacingCharacters(in: m.range, with: new.map { "\n" + $0 + "\n" } ?? "\n")
    }

    static func isDuoCLI(_ path: String) -> Bool { isDuoCLIPath(path) }
    public static func isDuoCLIPath(_ path: String) -> Bool { path.hasSuffix(".app/Contents/Helpers/duo2") }

    /// Keeps Duo's block when legacy's restore copies a whole CLAUDE.md back from its backup.
    public static func reapplyBlock(ifPresentIn before: String, to file: URL) {
        guard let b = firstBlock(in: before), let now = try? String(contentsOf: file, encoding: .utf8), firstBlock(in: now) == nil else { return }
        try? Data((now + (now.hasSuffix("\n") ? "\n" : "\n\n") + b + "\n").utf8).write(to: file, options: .atomic)
    }
}
