#!/usr/bin/env python3
"""Generate Sources/DuoKit/Design/Tokens.swift from docs/design/build-handoff/tokens.json.

tokens.json is the single source for colours, type, radii, sizes and spacing (handoff §4).
Run after any change to tokens.json:  python3 scripts/gen-tokens.py
"""
import json
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "docs/design/build-handoff/tokens.json"
dst = root / "Sources/DuoKit/Design/Tokens.swift"
t = json.loads(src.read_text())


def hex6(v):
    m = re.fullmatch(r"#([0-9A-Fa-f]{6})", v)
    if not m:
        raise SystemExit(f"Unsupported colour value {v!r}")
    return "0x" + m.group(1).upper()


light = t["color"]["light"]
console = t["color"]["console"]
dark = t["color"].get("darkProvisional", {})

lines = []
w = lines.append
w("// GENERATED by scripts/gen-tokens.py from docs/design/build-handoff/tokens.json. Do not edit.")
w("")
w("import AppKit")
w("import SwiftUI")
w("")
w("/// Semantic colours (handoff §4.1). Light chrome follows the appearance; the dark set is")
w("/// provisional and unapproved (§12 Q4), so the app forces light until Geoff signs one off.")
w("public enum DuoColor {")
for name, spec in light.items():
    if name.startswith("$"):
        continue
    d = dark.get(name, {}).get("value", spec["value"])
    use = spec.get("use", "")
    w(f"    /// {use}" if use else f"    /// {name}")
    alpha = f".withAlphaComponent({float(spec['alpha'])!r})" if "alpha" in spec else ""
    w(f"    public static let {name} = Color(nsColor: NSColor.duoDynamic(light: {hex6(spec['value'])}, dark: {hex6(d)}, name: \"{name}\"){alpha})")
w("")
w("    // Console chrome: the same in every appearance.")
for name, spec in console.items():
    if name.startswith("$"):
        continue
    use = spec.get("use", "")
    w(f"    /// {use}" if use else f"    /// {name}")
    w(f"    public static let {name} = Color(nsColor: .duoFixed({hex6(spec['value'])}))")
w("}")
w("")
w("public enum DuoNSColor {")
for name, spec in list(light.items()) + list(console.items()):
    if name.startswith("$"):
        continue
    if name in console:
        w(f"    public static let {name} = NSColor.duoFixed({hex6(spec['value'])})")
    else:
        d = dark.get(name, {}).get("value", spec["value"])
        alpha = f".withAlphaComponent({float(spec['alpha'])!r})" if "alpha" in spec else ""
        w(f"    public static let {name} = NSColor.duoDynamic(light: {hex6(spec['value'])}, dark: {hex6(d)}, name: \"{name}\"){alpha}")
w("}")
w("")


def num(v):
    return repr(float(v)) if isinstance(v, (int, float)) else None


w("/// Radii, borders and fixed sizes (handoff §4.3), in points.")
w("public enum DuoMetric {")
for k, v in t["radius"].items():
    if isinstance(v, dict):
        # Per-corner radii (chat-mode-handoff): a speech bubble's sharp corner.
        w(f"    public static let radius{k[0].upper() + k[1:]} = RectangleCornerRadii(topLeading: {num(v['topLeft'])}, bottomLeading: {num(v['bottomLeft'])}, bottomTrailing: {num(v['bottomRight'])}, topTrailing: {num(v['topRight'])})")
    else:
        w(f"    public static let radius{k[0].upper() + k[1:]}: CGFloat = {num(v)}")
for k, v in t["border"].items():
    if k.startswith("$") or not isinstance(v, (int, float)):
        continue   # notes, and the dash pattern (DuoShadow.dashPattern)
    w(f"    public static let border{k[0].upper() + k[1:]}: CGFloat = {num(v)}")
s = t["size"]
w(f"    public static let toolbarHeight: CGFloat = {num(s['toolbarHeight'])}")
w(f"    public static let tabStripHeight: CGFloat = {num(s['tabStripHeight'])}")
w(f"    public static let deckBarHeight: CGFloat = {num(s['deckBarHeight'])}")   # the PowerPoint viewer's bar (DL-125)
w(f"    public static let homeSessionTabsHeight: CGFloat = {num(s['homeSessionTabsHeight'])}")
w(f"    public static let overviewFooterHeight: CGFloat = {num(s['overviewFooterHeight'])}")
for k, v in s["row"].items():
    w(f"    public static let row{k[0].upper() + k[1:]}: CGFloat = {num(v)}")
w(f"    public static let buttonHeight: CGFloat = {num(s['buttonHeight'])}")
w(f"    public static let jumpFieldWidth: CGFloat = {num(s['jumpField']['width'])}")
w(f"    public static let jumpFieldHeight: CGFloat = {num(s['jumpField']['height'])}")
w(f"    public static let newProjectTileHeight: CGFloat = {num(s['newProjectTileHeight'])}")
w(f"    public static let glyph: CGFloat = {num(s['glyph'])}")
w(f"    public static let paneOverviewHome: CGFloat = {num(s['pane']['overview']['home'])}")
w(f"    public static let paneOverviewActionColumn: CGFloat = {num(s['pane']['overview']['actionColumn'])}")
w(f"    public static let paneProjectLeft: CGFloat = {num(s['pane']['project']['sessionsAndFiles'])}")
w(f"    public static let paneProjectRight: CGFloat = {num(s['pane']['project']['right'])}")
for k, v in s["paneMinimumProposed"].items():
    w(f"    public static let paneMin{k[0].upper() + k[1:]}: CGFloat = {num(v)}")
w(f"    public static let peekPopoverWidth: CGFloat = {num(s['peekPopoverWidth'])}")
# Search (search-handoff tokens-additions): the modal, its rows, preview and action menu.
for group, prefix in [("searchModal", "searchModal"), ("searchRow", "searchRow"), ("searchPreview", "searchPreview"), ("actionMenu", "actionMenu"), ("sheet", "sheet"), ("notice", "notice"), ("settings", "settings"), ("map", "map"), ("rowAction", "rowAction"), ("tabClose", "tabClose")]:
    for k, v in s[group].items():
        name = prefix + k[0].upper() + k[1:]
        if isinstance(v, (int, float)):
            w(f"    public static let {name}: CGFloat = {num(v)}")
        elif isinstance(v, dict) and all(isinstance(x, (int, float)) for x in v.values()):
            if {"top", "horizontal", "bottom"} <= v.keys():
                w(f"    public static let {name} = EdgeInsets(top: {num(v['top'])}, leading: {num(v['horizontal'])}, bottom: {num(v['bottom'])}, trailing: {num(v['horizontal'])})")
            else:
                for kk, vv in v.items():
                    w(f"    public static let {name}{kk[0].upper() + kk[1:]}: CGFloat = {num(vv)}")
# Surfaces slice 1 (surfaces-handoff): the idle list, console messages and bar.
ip = s["idlePopover"]
w(f"    public static let idlePopoverWidth: CGFloat = {num(ip['width'])}")
w(f"    public static let idlePopoverPadding = EdgeInsets(top: {num(ip['padding']['top'])}, leading: {num(ip['padding']['horizontal'])}, bottom: {num(ip['padding']['bottom'])}, trailing: {num(ip['padding']['horizontal'])})")
w(f"    public static let idleRowHeight: CGFloat = {num(ip['rowHeight'])}")
w(f"    public static let idleRowRadius: CGFloat = {num(ip['rowRadius'])}")
w(f"    public static let idleProjectColumnMax: CGFloat = {num(ip['projectColumnMax'])}")
w(f"    public static let idleAgeColumn: CGFloat = {num(ip['ageColumn'])}")
cm = s["consoleMessage"]
w(f"    public static let consoleMessagePadding: CGFloat = {num(cm['padding'])}")
w(f"    public static let consoleMessagePaddingHome = EdgeInsets(top: {num(cm['paddingInHomePane']['vertical'])}, leading: {num(cm['paddingInHomePane']['horizontal'])}, bottom: {num(cm['paddingInHomePane']['vertical'])}, trailing: {num(cm['paddingInHomePane']['horizontal'])})")
w(f"    public static let consoleMessageMaxTextWidth: CGFloat = {num(cm['maxTextWidth'])}")
w(f"    public static let consoleMessageGap: CGFloat = {num(cm['gap'])}")
w(f"    public static let consoleMessageButtonsTop: CGFloat = {num(cm['buttonsTop'])}")
w(f"    public static let consoleBarHeight: CGFloat = {num(s['consoleBar']['height'])}")
w(f"    public static let consoleBarPadding: CGFloat = {num(s['consoleBar']['paddingHorizontal'])}")
w(f"    public static let consoleTabTitleMax: Int = {int(s['consoleTabOverflow']['titleMaxCharacters'])}")
w(f"    public static let designWindow = CGSize(width: {num(s['designWindow']['width'])}, height: {num(s['designWindow']['height'])})")
w(f"    public static let minimumWindow = CGSize(width: {num(s['minimumWindow']['width'])}, height: {num(s['minimumWindow']['height'])})")
w("}")
w("")
w("/// Spacing (handoff §4.3), in points.")
w("public enum DuoSpace {")
sp = t["space"]
w(f"    public static let panePadding: CGFloat = {num(sp['panePadding'])}")
w(f"    public static let selectionInset: CGFloat = {num(sp['selectionInset'])}")
w(f"    public static let threadRuleX: CGFloat = {num(sp['threadRuleX'])}")
for k in ["chatColumnInset", "chatCardTrailing", "chatBubbleMax"]:   # chat-mode-handoff
    w(f"    public static let {k}: CGFloat = {num(sp[k])}")
for k in ["cardPadding", "pointerCardPadding", "questionBoxPadding", "buttonPadding", "popoverPadding", "documentPadding"]:
    p = sp[k]
    top = p.get("top", p.get("vertical"))
    bottom = p.get("bottom", p.get("vertical"))
    h = p["horizontal"]
    w(f"    public static let {k} = EdgeInsets(top: {num(top)}, leading: {num(h)}, bottom: {num(bottom)}, trailing: {num(h)})")
for k, v in sp["gap"].items():
    w(f"    public static let gap{k[0].upper() + k[1:]}: CGFloat = {num(v)}")
w("}")
w("")
w("/// The terminal's colours (surfaces-handoff DB-2): the 16 ANSI colours, an Increase Contrast set,")
w("/// cursor and selection. Contrast is against `console`.")
w("public enum DuoTerminalPalette {")
tp = t["terminal"]
order = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
         "brightBlack", "brightRed", "brightGreen", "brightYellow", "brightBlue", "brightMagenta", "brightCyan", "brightWhite"]
w("    public static let ansi: [NSColor] = [" + ", ".join(f".duoFixed({hex6(tp['ansi'][k]['value'])})" for k in order) + "]")
w("    public static let ansiIncreaseContrast: [NSColor] = [" + ", ".join(f".duoFixed({hex6(tp['ansiIncreaseContrast'][k]['value'])})" for k in order) + "]")
w(f"    public static let cursor = NSColor.duoFixed({hex6(tp['cursor']['value'])})")
w(f"    public static let textUnderCursor = NSColor.duoFixed({hex6(tp['cursor']['textUnderCursor'])})")
w(f"    public static let selection = NSColor.duoFixed({hex6(tp['selection']['value'])})")
w("}")
w("")
w("/// Type styles (handoff §4.2).")
w("public enum DuoTextStyle: CaseIterable, Sendable {")
styles = t["font"]["style"]
for k in styles:
    w(f"    case {k}")
w("")
w("    public var spec: DuoTextSpec {")
w("        switch self {")
for k, v in styles.items():
    weight = {"regular": ".regular", "medium": ".medium", "semibold": ".semibold", "bold": ".bold"}[v["weight"]]
    mono = "true" if v["family"] == "mono" else "false"
    tracking = num(v.get("tracking", 0))
    upper = "true" if v.get("textCase") == "uppercase" else "false"
    w(f"        case .{k}: DuoTextSpec(size: {num(v['size'])}, lineHeight: {num(v['lineHeight'])}, weight: {weight}, mono: {mono}, tracking: {tracking}, uppercase: {upper})")
w("        }")
w("    }")
w("}")
w("")
w("/// Motion (DL-129, DL-130), in seconds. None of it runs with Reduce Motion; build it with `DuoMotionToken`.")
w("public enum DuoMotion {")
motion = [(k, v) for k, v in t["motion"].items() if not k.startswith("$")]
for k, v in motion:
    w(f"    public static let {k}: Double = {v!r}")
w("}")
w("")
w("/// How a motion eases (DL-130): arriving eases out, leaving eases in, moving eases in and out.")
w("public enum DuoEase: Sendable { case out, `in`, inOut, none }")
w("")
w("/// One motion token: its duration and its easing.")
w("public enum DuoMotionToken: String, CaseIterable, Sendable {")
w("    case " + ", ".join(k for k, _ in motion))
w("    public var seconds: Double {")
w("        switch self {")
for k, _ in motion:
    w(f"        case .{k}: DuoMotion.{k}")
w("        }")
w("    }")
w("    public var ease: DuoEase {")
w("        switch self {")
eases = t["motionEase"]
for k, _ in motion:
    e = eases[k]
    w(f"        case .{k}: .{'`in`' if e == 'in' else e}")
w("        }")
w("    }")
w("}")
w("")
w("/// The popover shadow (handoff §4.5): search, the action menu, the idle list, drag cards.")
w("public enum DuoShadow {")
sh = t["shadow"]["popover"]
m = re.fullmatch(r"rgba\((\d+),\s*(\d+),\s*(\d+),\s*([0-9.]+)\)", sh["color"].replace(" ", ""))
w(f"    public static let popoverColor = Color(.sRGB, red: {int(m.group(1))}/255, green: {int(m.group(2))}/255, blue: {int(m.group(3))}/255, opacity: {float(m.group(4))!r})")
w(f"    /// SwiftUI's radius is half the CSS blur.")
w(f"    public static let popoverRadius: CGFloat = {num(sh['blur'] / 2)}")
w(f"    public static let popoverX: CGFloat = {num(sh['x'])}")
w(f"    public static let popoverY: CGFloat = {num(sh['y'])}")
w(f"    /// Dashed borders (New project tile, drop targets): on, off.")
w(f"    public static let dashPattern: [CGFloat] = [{', '.join(num(x) for x in t['border']['dash'])}]")
w("}")
w("")
w("extension View {")
w("    /// The popover shadow from tokens.json.")
w("    public func duoPopoverShadow() -> some View { shadow(color: DuoShadow.popoverColor, radius: DuoShadow.popoverRadius, x: DuoShadow.popoverX, y: DuoShadow.popoverY) }")
w("}")
w("")
w("/// Glyph and icon paths in a 10x10 (or stated) view box (handoff §4.4).")
w("public enum DuoGlyphPath {")
for k, v in t["glyph"].items():
    if k.startswith("$") or k == "onConsole":
        continue
    w(f"    public static let {k} = {json.dumps(v['svg'])}")
w("}")
w("")

dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text("\n".join(lines))
print(f"wrote {dst.relative_to(root)}")
