#!/usr/bin/env python3
"""Generate video/style/tokens.json from the app's tokens (docs/design/build-handoff/tokens.json)
plus the video's own tokens (video/style/video-tokens.json). Never edit the output by hand (DL-169)."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
app = json.loads((root / "docs/design/build-handoff/tokens.json").read_text())
own = json.loads((root / "video/style/video-tokens.json").read_text())


def values(d):
    return {k: v["value"] for k, v in d.items() if isinstance(v, dict) and "value" in v}


out = {
    "$note": "Generated by scripts/gen-video-tokens.py from the app's tokens and video/style/video-tokens.json. Don't edit.",
    "color": {name: values(group) for name, group in app["color"].items() if isinstance(group, dict)},
    "font": {"ui": app["font"]["family"]["ui"]["css"], "mono": app["font"]["family"]["mono"]["css"]},
    "appMotion": {k: v for k, v in app["motion"].items() if not k.startswith("$")},
    "appMotionEase": {k: v for k, v in app["motionEase"].items() if not k.startswith("$")},
    **{k: v for k, v in own.items() if not k.startswith("$")},
}
(root / "video/style/tokens.json").write_text(json.dumps(out, indent=2) + "\n")
print("wrote video/style/tokens.json")
